OPENAI_API_KEY = "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"

[snowflake]
user = 'SNOWGPT'        
password = 'SnowGPT@202308'
account = 'anblicksorg_aws.us-east-1'
warehouse = 'SNOWGPT_WH'
database = 'SNOWGPT_DB'
schema = 'STG' 
