OPENAI_API_KEY = "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"

[snowflake]
user = 'SNOWGPT'        
password = 'SnowGPT@202308'
account = 'anblicksorg_aws.us-east-1'
warehouse = 'SNOWGPT_WH'
database = 'SNOWGPT_DB'
schema = 'STG' 
client_session_keep_alive = true